name: Deploy WordPress Theme

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Tailwind CSS
      run: npm install tailwindcss @tailwindcss/typography

    - name: Build Tailwind CSS
      run: npx tailwindcss -i ./tailwind.css -o ./build/index.css --minify

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: |
        rsync -av --delete $GITHUB_WORKSPACE/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/wordpress/wp-content/themes/yk-theme
